APISuite/apisuite-fe

- src/components/SubscriptionsModal/SubscriptionsModal.tsx
- src/containers/App/routes.tsx
- src/containers/Applications/Applications.tsx
API Product Subscription's 'Review app' button was resulting in a '404 Not Found'.
> (APIS-762) FE - Subscriptions: Review App button in overlay gives a 404 error

- extensions.cloud.json
- extensions.dev.json
- extensions.stg.json
Just updating the `extensions.(...).json` files following a patch of the Admin area's extension.
> chore: Bump of Admin area's extension version

- src/components/ApplicationsModal/ApplicationsModal.tsx
- src/components/ApplicationsModal/styles.ts
- src/containers/Applications/ducks.ts
- src/containers/Applications/sagas.ts
- src/containers/Applications/types.ts
- src/language/translations/en-US.json
Added a **Labels** field to the App creation/updating process, so as to allow the App Marketplace to display labels, and have filtering based on these.
> (APXM-58) - FE: Changes for the App Marketplace, Part 2

- extensions.dev.json
- extensions.stg.json
- src/containers/Applications/Applications.tsx
- src/containers/Applications/styles.ts
- src/language/translations/en-US.json
Redesigned the 'Applications' view to account for Marketplace apps.
> (APXM-30) - FE: Applications view redesign to account for subscribed Marketplace apps

- src/components/Navigation/useMenu.tsx
Fixed the Marketplace extension's tab placement on the CORE's navigation menu.
> (APXM-62) - FE: Marketplace's tab placement incorrect for logged out user

- extensions.cloud.json
- extensions.dev.json
- extensions.prod.json
- extensions.stg.json
- package-lock.json
- package.json
see [APIS-826](https://cloudoki.atlassian.net/browse/APIS-826)
Note: The actual fix was made on the extension repo. This is just a bump of versions that are compatible.
> fix: upgrade fe-base version to work with cloud extension

- src/components/Navigation/useMenu.tsx
Navigation was misbehaving for logged-out users (got stuck in 'Marketplace', regardless of your location on the project).
> hotfix: Navigation fix

- extensions.dev.json
- extensions.ts
Included Billing extension to CORE, and updated Marketplace version.
> feat: Billing extension inclusion

- package-lock.json
- package.json
- src/components/InvitationForm/InvitationForm.tsx
- src/components/InvitationForm/LoadingView.tsx
- src/components/InvitationForm/styles.ts
- src/language/translations/en-US.json
- src/pages/SignInOrUp/SignInOrUp.tsx
- src/pages/SignInOrUp/styles.ts
- src/store/auth/actions/invitation.ts
- src/store/auth/actions/types.d.ts
- src/store/auth/middleware.ts
- src/store/auth/sagas.ts
- add non sso invitation flow (new user, existing user, logged user);
- restore the registration confirmation saga (missing);
- add buttons instead of message when in sso and in sign in/up views;
- audit fixes;
> feat(non-sso-invitation): add non sso invitation flow, restore registration confirm flow saga

- src/components/InvitationForm/InvitationForm.tsx
- src/components/InvitationForm/styles.ts
- src/language/translations/en-US.json
- src/pages/SignInOrUp/SignInOrUp.tsx
- src/store/auth/middleware.ts
- fix reject invitation: add missing dispatch in function, add success event in middleware
- add missing footer url: add forgot password to invitation to existing user without active session, add privacy policy for new invited account
> fix(invitation-flow): add missing footer url, fix reject invitation

- src/components/APICatalog/APICatalog.tsx
- src/pages/APIProducts/APIProducts.tsx
see [APIS-791](https://cloudoki.atlassian.net/browse/APIS-791)
> fix(APIProducts): extra `v` char when no version available

- src/language/translations/en-US.json
see [APIS-872](https://cloudoki.atlassian.net/browse/APIS-872)
> fix(translations): typo

- src/language/translations/en-US.json
- src/pages/Dashboard/Dashboard.tsx
- src/pages/Sandbox/Sandbox.tsx
see [APIS-872](https://cloudoki.atlassian.net/browse/APIS-872)
> fix: translations typos and space incorrections

- src/pages/Profile/Profile.tsx
- src/pages/Profile/selectors.ts
- src/pages/Profile/styles.ts
- src/store/profile/reducer.ts
- src/store/profile/sagas.ts
- src/store/profile/types.d.ts
Added redirect to IdP (i.e., Keycloak) so as to change one's details.
> (APXM-75) - FE: Give user ability to access Keycloak URL for account update

- src/components/ApplicationsModal/ApplicationsModal.tsx
- src/components/ApplicationsModal/styles.ts
Fixed an issue with the apps' overlay that was related to custom properties (the issue being lack of custom properties causing inability to create apps).
> fix: Issue with the apps' overlay related to custom properties

- src/components/Navigation/useMenu.tsx
see [APIS-923](https://cloudoki.atlassian.net/browse/APIS-923)
> fix: applications label copy

- src/components/ApplicationsModal/ApplicationsModal.tsx
- remove media upload for new apps
- update disabled button state based on changed value from publishing section
Closes [APIS-928](https://cloudoki.atlassian.net/browse/APIS-928)
> fix(app-overlay): publishing state and media upload

- src/components/APICatalog/APICatalog.tsx
- src/components/ActionsCatalog/ActionsCatalog.tsx
- src/components/ActionsCatalog/styles.ts
- src/components/Carousel/Carousel.tsx
- src/components/SignInForm/SignInForm.tsx
- src/components/SignInForm/selector.ts
- src/language/translations/en-US.json
- src/pages/Dashboard/Dashboard.tsx
Inconsequential changes. To be continued when convenient, but feel free to review, approve, and merge.
> Small changes/improvements to tackle some 'fixmes' and 'to-dos'

- src/components/ApplicationsModal/ApplicationsModal.tsx
- src/pages/Applications/Applications.tsx
- src/pages/Applications/selector.ts
Fixed the 'App Listing' view's inability to re-render upon creation/deletion of apps.
> (APIS-942/944) - FE: App list not updated after app created/deleted

- src/components/ApplicationsModal/ApplicationsModal.tsx
- src/pages/Applications/Applications.tsx
- src/store/applications/actions/types.d.ts
- src/store/applications/sagas.ts
Fixed duplicate API requests on 'App Listing' view.
Also corrected the endpoint used to retrieve an app's details.
> (APIS-785) - FE: Duplicate/wrong API requests on app views

- src/components/ApplicationsModal/ApplicationsModal.tsx
- src/store/applications/reducer.ts
- src/store/applications/sagas.ts
- src/store/applications/types.d.ts
- src/util/extensions.ts
Made necessary changes to allow for the use of an 'Application URL' input field.
> feat: Made necessary changes to allow for the use of an 'Application URL' input field

- src/pages/Applications/Applications.tsx
- src/pages/Profile/Profile.tsx
- src/pages/Profile/selectors.ts
- src/pages/Profile/styles.ts
Closes [MEPE-55](https://cloudoki.atlassian.net/browse/MEPE-55)
Closes [MEPE-56](https://cloudoki.atlassian.net/browse/MEPE-56)
> fix(org-access): fix organisation access for base users

- src/components/SignUpForm/SignUpForm.tsx
Skipping on the sign up's org details step was not working as expected.
> fix: Corrected an issue related to skipping on the sign up form's org details

- src/components/Navigation/Navigation.tsx
- src/components/Navigation/selector.ts
see [APIS-964](https://cloudoki.atlassian.net/browse/APIS-964)
> perf(Navigation): react to current org role change

- src/pages/Profile/Profile.tsx
see [APIS-967](https://cloudoki.atlassian.net/browse/APIS-967)
> fix(Profile): editable email

- src/components/APICatalog/APICatalog.tsx
- src/components/APICatalog/styles.ts
- src/components/APICatalog/types.d.ts
- src/components/ApplicationCard/ApplicationCard.tsx
- src/components/ApplicationCard/types.d.ts
- src/pages/Dashboard/Dashboard.tsx
- src/pages/Sandbox/Sandbox.tsx
Closes:
- [APIS-972](https://cloudoki.atlassian.net/browse/APIS-972)
- [APIS-965](https://cloudoki.atlassian.net/browse/APIS-965)
> fix(api-catalog): update style and add limit

- src/pages/APIProducts/APIProducts.tsx
- src/pages/Applications/Applications.tsx
- src/pages/Subscriptions/Subscriptions.tsx
- src/store/applications/actions/types.d.ts
- src/store/applications/sagas.ts
see [APIS-962](https://cloudoki.atlassian.net/browse/APIS-962)
> fix(SubscriptionsModal): request access enabled after requesting access

- cypress.json
- cypress/fixtures/settings/settings.json
- cypress/integration/Core/Dashboard_01.spec.ts
- src/pages/APIProducts/APIProducts.tsx
- src/pages/APIProducts/styles.ts
see [APIS-981](https://cloudoki.atlassian.net/browse/APIS-981)
> perf(APIProducts): use Typography when possible

- src/pages/APIDetails/APIDetails.tsx
- src/pages/APIDetails/styles.ts
see [APIS-983](https://cloudoki.atlassian.net/browse/APIS-983)
> perf(APIDetails): use Typography when possible

- src/components/ApplicationsModal/ApplicationsModal.tsx
- src/language/translations/en-US.json
Also, changed translations to better reflect the contents one can upload (image files only, no video).
> fix: Fixed the ability to upload unsupported files (e.g., SVG)

- src/components/APICatalog/APICatalog.tsx
- src/components/APICatalog/styles.ts
- src/components/APICatalog/types.d.ts
- src/language/translations/en-US.json
- src/pages/APIProducts/APIProducts.tsx
- src/pages/Dashboard/Dashboard.tsx
- src/pages/Sandbox/Sandbox.tsx
Refer to https://cloudoki.atlassian.net/browse/APIS-1015 for designs.
> fix: Fixed API Product cards to contain their name & their contract title

- src/language/translations/en-US.json
- src/pages/Profile/Profile.tsx
You should now be able to go from a base user to an org owner.
> feat: Added support for 'base user-to-org owner' role upgrade

- src/language/translations/en-US.json
- src/pages/TeamPage/TeamPage.tsx
- src/store/index.ts
- src/store/profile/actions/removeTeamMember.ts
- src/store/profile/actions/types.d.ts
- src/store/profile/middleware.ts
- src/store/profile/reducer.ts
- src/store/profile/sagas.ts
- src/store/profile/types.d.ts
Added what remained of the team removal feature according to BE's specified conditions (that you may review here - https://cloudoki.atlassian.net/browse/APIS-1070).
> (APIS-1033) FE: Team - Can't access remove user option
